// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ADMINAUDITLOGS_SCHEMATAS_H_
#define FLATBUFFERS_GENERATED_ADMINAUDITLOGS_SCHEMATAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace schematas {

struct AdminAuditLog;
struct AdminAuditLogBuilder;

struct AdminAuditLogList;
struct AdminAuditLogListBuilder;

struct AdminAuditLog FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AdminAuditLogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_USERNAME = 6,
    VT_ACTION = 8,
    VT_DETAILS = 10,
    VT_TS = 12,
    VT_TS_UNIX_MS = 14
  };
  int64_t id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *username() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USERNAME);
  }
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  const ::flatbuffers::String *details() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DETAILS);
  }
  const ::flatbuffers::String *ts() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TS);
  }
  int64_t ts_unix_ms() const {
    return GetField<int64_t>(VT_TS_UNIX_MS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_USERNAME) &&
           verifier.VerifyString(username()) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyOffset(verifier, VT_DETAILS) &&
           verifier.VerifyString(details()) &&
           VerifyOffset(verifier, VT_TS) &&
           verifier.VerifyString(ts()) &&
           VerifyField<int64_t>(verifier, VT_TS_UNIX_MS, 8) &&
           verifier.EndTable();
  }
};

struct AdminAuditLogBuilder {
  typedef AdminAuditLog Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int64_t id) {
    fbb_.AddElement<int64_t>(AdminAuditLog::VT_ID, id, 0);
  }
  void add_username(::flatbuffers::Offset<::flatbuffers::String> username) {
    fbb_.AddOffset(AdminAuditLog::VT_USERNAME, username);
  }
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(AdminAuditLog::VT_ACTION, action);
  }
  void add_details(::flatbuffers::Offset<::flatbuffers::String> details) {
    fbb_.AddOffset(AdminAuditLog::VT_DETAILS, details);
  }
  void add_ts(::flatbuffers::Offset<::flatbuffers::String> ts) {
    fbb_.AddOffset(AdminAuditLog::VT_TS, ts);
  }
  void add_ts_unix_ms(int64_t ts_unix_ms) {
    fbb_.AddElement<int64_t>(AdminAuditLog::VT_TS_UNIX_MS, ts_unix_ms, 0);
  }
  explicit AdminAuditLogBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AdminAuditLog> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AdminAuditLog>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AdminAuditLog> CreateAdminAuditLog(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> username = 0,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    ::flatbuffers::Offset<::flatbuffers::String> details = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ts = 0,
    int64_t ts_unix_ms = 0) {
  AdminAuditLogBuilder builder_(_fbb);
  builder_.add_ts_unix_ms(ts_unix_ms);
  builder_.add_id(id);
  builder_.add_ts(ts);
  builder_.add_details(details);
  builder_.add_action(action);
  builder_.add_username(username);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AdminAuditLog> CreateAdminAuditLogDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    const char *username = nullptr,
    const char *action = nullptr,
    const char *details = nullptr,
    const char *ts = nullptr,
    int64_t ts_unix_ms = 0) {
  auto username__ = username ? _fbb.CreateString(username) : 0;
  auto action__ = action ? _fbb.CreateString(action) : 0;
  auto details__ = details ? _fbb.CreateString(details) : 0;
  auto ts__ = ts ? _fbb.CreateString(ts) : 0;
  return schematas::CreateAdminAuditLog(
      _fbb,
      id,
      username__,
      action__,
      details__,
      ts__,
      ts_unix_ms);
}

struct AdminAuditLogList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AdminAuditLogListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOGS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::AdminAuditLog>> *logs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::AdminAuditLog>> *>(VT_LOGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LOGS) &&
           verifier.VerifyVector(logs()) &&
           verifier.VerifyVectorOfTables(logs()) &&
           verifier.EndTable();
  }
};

struct AdminAuditLogListBuilder {
  typedef AdminAuditLogList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_logs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::AdminAuditLog>>> logs) {
    fbb_.AddOffset(AdminAuditLogList::VT_LOGS, logs);
  }
  explicit AdminAuditLogListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AdminAuditLogList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AdminAuditLogList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AdminAuditLogList> CreateAdminAuditLogList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::AdminAuditLog>>> logs = 0) {
  AdminAuditLogListBuilder builder_(_fbb);
  builder_.add_logs(logs);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AdminAuditLogList> CreateAdminAuditLogListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<schematas::AdminAuditLog>> *logs = nullptr) {
  auto logs__ = logs ? _fbb.CreateVector<::flatbuffers::Offset<schematas::AdminAuditLog>>(*logs) : 0;
  return schematas::CreateAdminAuditLogList(
      _fbb,
      logs__);
}

inline const schematas::AdminAuditLogList *GetAdminAuditLogList(const void *buf) {
  return ::flatbuffers::GetRoot<schematas::AdminAuditLogList>(buf);
}

inline const schematas::AdminAuditLogList *GetSizePrefixedAdminAuditLogList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schematas::AdminAuditLogList>(buf);
}

inline bool VerifyAdminAuditLogListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schematas::AdminAuditLogList>(nullptr);
}

inline bool VerifySizePrefixedAdminAuditLogListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schematas::AdminAuditLogList>(nullptr);
}

inline void FinishAdminAuditLogListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::AdminAuditLogList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAdminAuditLogListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::AdminAuditLogList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schematas

#endif  // FLATBUFFERS_GENERATED_ADMINAUDITLOGS_SCHEMATAS_H_
