// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DLQ_SCHEMATAS_H_
#define FLATBUFFERS_GENERATED_DLQ_SCHEMATAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace schematas {

struct DLQEntry;
struct DLQEntryBuilder;

struct DLQEntryList;
struct DLQEntryListBuilder;

struct DLQEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DLQEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PACKAGE_ID = 6,
    VT_PAYLOAD = 8,
    VT_ERROR_CODE = 10,
    VT_ERROR_MESSAGE = 12,
    VT_FAILED_AT = 14,
    VT_FAILED_AT_UNIX_MS = 16,
    VT_RESOLVED = 18,
    VT_RESOLVED_AT = 20,
    VT_RESOLVED_AT_UNIX_MS = 22
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *package_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PACKAGE_ID);
  }
  const ::flatbuffers::String *payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD);
  }
  const ::flatbuffers::String *error_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_CODE);
  }
  const ::flatbuffers::String *error_message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MESSAGE);
  }
  const ::flatbuffers::String *failed_at() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FAILED_AT);
  }
  int64_t failed_at_unix_ms() const {
    return GetField<int64_t>(VT_FAILED_AT_UNIX_MS, 0);
  }
  bool resolved() const {
    return GetField<uint8_t>(VT_RESOLVED, 0) != 0;
  }
  const ::flatbuffers::String *resolved_at() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RESOLVED_AT);
  }
  int64_t resolved_at_unix_ms() const {
    return GetField<int64_t>(VT_RESOLVED_AT_UNIX_MS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_PACKAGE_ID) &&
           verifier.VerifyString(package_id()) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           VerifyOffset(verifier, VT_ERROR_CODE) &&
           verifier.VerifyString(error_code()) &&
           VerifyOffset(verifier, VT_ERROR_MESSAGE) &&
           verifier.VerifyString(error_message()) &&
           VerifyOffset(verifier, VT_FAILED_AT) &&
           verifier.VerifyString(failed_at()) &&
           VerifyField<int64_t>(verifier, VT_FAILED_AT_UNIX_MS, 8) &&
           VerifyField<uint8_t>(verifier, VT_RESOLVED, 1) &&
           VerifyOffset(verifier, VT_RESOLVED_AT) &&
           verifier.VerifyString(resolved_at()) &&
           VerifyField<int64_t>(verifier, VT_RESOLVED_AT_UNIX_MS, 8) &&
           verifier.EndTable();
  }
};

struct DLQEntryBuilder {
  typedef DLQEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(DLQEntry::VT_ID, id);
  }
  void add_package_id(::flatbuffers::Offset<::flatbuffers::String> package_id) {
    fbb_.AddOffset(DLQEntry::VT_PACKAGE_ID, package_id);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::String> payload) {
    fbb_.AddOffset(DLQEntry::VT_PAYLOAD, payload);
  }
  void add_error_code(::flatbuffers::Offset<::flatbuffers::String> error_code) {
    fbb_.AddOffset(DLQEntry::VT_ERROR_CODE, error_code);
  }
  void add_error_message(::flatbuffers::Offset<::flatbuffers::String> error_message) {
    fbb_.AddOffset(DLQEntry::VT_ERROR_MESSAGE, error_message);
  }
  void add_failed_at(::flatbuffers::Offset<::flatbuffers::String> failed_at) {
    fbb_.AddOffset(DLQEntry::VT_FAILED_AT, failed_at);
  }
  void add_failed_at_unix_ms(int64_t failed_at_unix_ms) {
    fbb_.AddElement<int64_t>(DLQEntry::VT_FAILED_AT_UNIX_MS, failed_at_unix_ms, 0);
  }
  void add_resolved(bool resolved) {
    fbb_.AddElement<uint8_t>(DLQEntry::VT_RESOLVED, static_cast<uint8_t>(resolved), 0);
  }
  void add_resolved_at(::flatbuffers::Offset<::flatbuffers::String> resolved_at) {
    fbb_.AddOffset(DLQEntry::VT_RESOLVED_AT, resolved_at);
  }
  void add_resolved_at_unix_ms(int64_t resolved_at_unix_ms) {
    fbb_.AddElement<int64_t>(DLQEntry::VT_RESOLVED_AT_UNIX_MS, resolved_at_unix_ms, 0);
  }
  explicit DLQEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DLQEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DLQEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DLQEntry> CreateDLQEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> package_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> payload = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error_message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> failed_at = 0,
    int64_t failed_at_unix_ms = 0,
    bool resolved = false,
    ::flatbuffers::Offset<::flatbuffers::String> resolved_at = 0,
    int64_t resolved_at_unix_ms = 0) {
  DLQEntryBuilder builder_(_fbb);
  builder_.add_resolved_at_unix_ms(resolved_at_unix_ms);
  builder_.add_failed_at_unix_ms(failed_at_unix_ms);
  builder_.add_resolved_at(resolved_at);
  builder_.add_failed_at(failed_at);
  builder_.add_error_message(error_message);
  builder_.add_error_code(error_code);
  builder_.add_payload(payload);
  builder_.add_package_id(package_id);
  builder_.add_id(id);
  builder_.add_resolved(resolved);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DLQEntry> CreateDLQEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *package_id = nullptr,
    const char *payload = nullptr,
    const char *error_code = nullptr,
    const char *error_message = nullptr,
    const char *failed_at = nullptr,
    int64_t failed_at_unix_ms = 0,
    bool resolved = false,
    const char *resolved_at = nullptr,
    int64_t resolved_at_unix_ms = 0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto package_id__ = package_id ? _fbb.CreateString(package_id) : 0;
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  auto error_code__ = error_code ? _fbb.CreateString(error_code) : 0;
  auto error_message__ = error_message ? _fbb.CreateString(error_message) : 0;
  auto failed_at__ = failed_at ? _fbb.CreateString(failed_at) : 0;
  auto resolved_at__ = resolved_at ? _fbb.CreateString(resolved_at) : 0;
  return schematas::CreateDLQEntry(
      _fbb,
      id__,
      package_id__,
      payload__,
      error_code__,
      error_message__,
      failed_at__,
      failed_at_unix_ms,
      resolved,
      resolved_at__,
      resolved_at_unix_ms);
}

struct DLQEntryList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DLQEntryListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::DLQEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::DLQEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct DLQEntryListBuilder {
  typedef DLQEntryList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::DLQEntry>>> entries) {
    fbb_.AddOffset(DLQEntryList::VT_ENTRIES, entries);
  }
  explicit DLQEntryListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DLQEntryList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DLQEntryList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DLQEntryList> CreateDLQEntryList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::DLQEntry>>> entries = 0) {
  DLQEntryListBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DLQEntryList> CreateDLQEntryListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<schematas::DLQEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<schematas::DLQEntry>>(*entries) : 0;
  return schematas::CreateDLQEntryList(
      _fbb,
      entries__);
}

inline const schematas::DLQEntryList *GetDLQEntryList(const void *buf) {
  return ::flatbuffers::GetRoot<schematas::DLQEntryList>(buf);
}

inline const schematas::DLQEntryList *GetSizePrefixedDLQEntryList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schematas::DLQEntryList>(buf);
}

inline bool VerifyDLQEntryListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schematas::DLQEntryList>(nullptr);
}

inline bool VerifySizePrefixedDLQEntryListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schematas::DLQEntryList>(nullptr);
}

inline void FinishDLQEntryListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::DLQEntryList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDLQEntryListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::DLQEntryList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schematas

#endif  // FLATBUFFERS_GENERATED_DLQ_SCHEMATAS_H_
