// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_JOBAUDITLOGS_SCHEMATAS_H_
#define FLATBUFFERS_GENERATED_JOBAUDITLOGS_SCHEMATAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace schematas {

struct JobAuditLog;
struct JobAuditLogBuilder;

struct JobAuditLogList;
struct JobAuditLogListBuilder;

struct JobAuditLog FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JobAuditLogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_RUN_ID = 6,
    VT_COMPONENT = 8,
    VT_MESSAGE = 10,
    VT_TS = 12,
    VT_TS_UNIX_MS = 14
  };
  int64_t id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  int64_t run_id() const {
    return GetField<int64_t>(VT_RUN_ID, 0);
  }
  const ::flatbuffers::String *component() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPONENT);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *ts() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TS);
  }
  int64_t ts_unix_ms() const {
    return GetField<int64_t>(VT_TS_UNIX_MS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_RUN_ID, 8) &&
           VerifyOffset(verifier, VT_COMPONENT) &&
           verifier.VerifyString(component()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_TS) &&
           verifier.VerifyString(ts()) &&
           VerifyField<int64_t>(verifier, VT_TS_UNIX_MS, 8) &&
           verifier.EndTable();
  }
};

struct JobAuditLogBuilder {
  typedef JobAuditLog Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int64_t id) {
    fbb_.AddElement<int64_t>(JobAuditLog::VT_ID, id, 0);
  }
  void add_run_id(int64_t run_id) {
    fbb_.AddElement<int64_t>(JobAuditLog::VT_RUN_ID, run_id, 0);
  }
  void add_component(::flatbuffers::Offset<::flatbuffers::String> component) {
    fbb_.AddOffset(JobAuditLog::VT_COMPONENT, component);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(JobAuditLog::VT_MESSAGE, message);
  }
  void add_ts(::flatbuffers::Offset<::flatbuffers::String> ts) {
    fbb_.AddOffset(JobAuditLog::VT_TS, ts);
  }
  void add_ts_unix_ms(int64_t ts_unix_ms) {
    fbb_.AddElement<int64_t>(JobAuditLog::VT_TS_UNIX_MS, ts_unix_ms, 0);
  }
  explicit JobAuditLogBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<JobAuditLog> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<JobAuditLog>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<JobAuditLog> CreateJobAuditLog(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    int64_t run_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> component = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ts = 0,
    int64_t ts_unix_ms = 0) {
  JobAuditLogBuilder builder_(_fbb);
  builder_.add_ts_unix_ms(ts_unix_ms);
  builder_.add_run_id(run_id);
  builder_.add_id(id);
  builder_.add_ts(ts);
  builder_.add_message(message);
  builder_.add_component(component);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<JobAuditLog> CreateJobAuditLogDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    int64_t run_id = 0,
    const char *component = nullptr,
    const char *message = nullptr,
    const char *ts = nullptr,
    int64_t ts_unix_ms = 0) {
  auto component__ = component ? _fbb.CreateString(component) : 0;
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto ts__ = ts ? _fbb.CreateString(ts) : 0;
  return schematas::CreateJobAuditLog(
      _fbb,
      id,
      run_id,
      component__,
      message__,
      ts__,
      ts_unix_ms);
}

struct JobAuditLogList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JobAuditLogListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOGS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::JobAuditLog>> *logs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::JobAuditLog>> *>(VT_LOGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LOGS) &&
           verifier.VerifyVector(logs()) &&
           verifier.VerifyVectorOfTables(logs()) &&
           verifier.EndTable();
  }
};

struct JobAuditLogListBuilder {
  typedef JobAuditLogList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_logs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::JobAuditLog>>> logs) {
    fbb_.AddOffset(JobAuditLogList::VT_LOGS, logs);
  }
  explicit JobAuditLogListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<JobAuditLogList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<JobAuditLogList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<JobAuditLogList> CreateJobAuditLogList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::JobAuditLog>>> logs = 0) {
  JobAuditLogListBuilder builder_(_fbb);
  builder_.add_logs(logs);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<JobAuditLogList> CreateJobAuditLogListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<schematas::JobAuditLog>> *logs = nullptr) {
  auto logs__ = logs ? _fbb.CreateVector<::flatbuffers::Offset<schematas::JobAuditLog>>(*logs) : 0;
  return schematas::CreateJobAuditLogList(
      _fbb,
      logs__);
}

inline const schematas::JobAuditLogList *GetJobAuditLogList(const void *buf) {
  return ::flatbuffers::GetRoot<schematas::JobAuditLogList>(buf);
}

inline const schematas::JobAuditLogList *GetSizePrefixedJobAuditLogList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schematas::JobAuditLogList>(buf);
}

inline bool VerifyJobAuditLogListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schematas::JobAuditLogList>(nullptr);
}

inline bool VerifySizePrefixedJobAuditLogListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schematas::JobAuditLogList>(nullptr);
}

inline void FinishJobAuditLogListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::JobAuditLogList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedJobAuditLogListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::JobAuditLogList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schematas

#endif  // FLATBUFFERS_GENERATED_JOBAUDITLOGS_SCHEMATAS_H_
