// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYSTEMLOGS_SCHEMATAS_H_
#define FLATBUFFERS_GENERATED_SYSTEMLOGS_SCHEMATAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace schematas {

struct SystemLog;
struct SystemLogBuilder;

struct SystemLogList;
struct SystemLogListBuilder;

struct SystemLog FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SystemLogBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_LEVEL = 6,
    VT_COMPONENT = 8,
    VT_MESSAGE = 10,
    VT_TS = 12,
    VT_TS_UNIX_MS = 14
  };
  int64_t id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *level() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LEVEL);
  }
  const ::flatbuffers::String *component() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPONENT);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *ts() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TS);
  }
  int64_t ts_unix_ms() const {
    return GetField<int64_t>(VT_TS_UNIX_MS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_LEVEL) &&
           verifier.VerifyString(level()) &&
           VerifyOffset(verifier, VT_COMPONENT) &&
           verifier.VerifyString(component()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_TS) &&
           verifier.VerifyString(ts()) &&
           VerifyField<int64_t>(verifier, VT_TS_UNIX_MS, 8) &&
           verifier.EndTable();
  }
};

struct SystemLogBuilder {
  typedef SystemLog Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int64_t id) {
    fbb_.AddElement<int64_t>(SystemLog::VT_ID, id, 0);
  }
  void add_level(::flatbuffers::Offset<::flatbuffers::String> level) {
    fbb_.AddOffset(SystemLog::VT_LEVEL, level);
  }
  void add_component(::flatbuffers::Offset<::flatbuffers::String> component) {
    fbb_.AddOffset(SystemLog::VT_COMPONENT, component);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(SystemLog::VT_MESSAGE, message);
  }
  void add_ts(::flatbuffers::Offset<::flatbuffers::String> ts) {
    fbb_.AddOffset(SystemLog::VT_TS, ts);
  }
  void add_ts_unix_ms(int64_t ts_unix_ms) {
    fbb_.AddElement<int64_t>(SystemLog::VT_TS_UNIX_MS, ts_unix_ms, 0);
  }
  explicit SystemLogBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SystemLog> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SystemLog>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SystemLog> CreateSystemLog(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> level = 0,
    ::flatbuffers::Offset<::flatbuffers::String> component = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ts = 0,
    int64_t ts_unix_ms = 0) {
  SystemLogBuilder builder_(_fbb);
  builder_.add_ts_unix_ms(ts_unix_ms);
  builder_.add_id(id);
  builder_.add_ts(ts);
  builder_.add_message(message);
  builder_.add_component(component);
  builder_.add_level(level);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SystemLog> CreateSystemLogDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    const char *level = nullptr,
    const char *component = nullptr,
    const char *message = nullptr,
    const char *ts = nullptr,
    int64_t ts_unix_ms = 0) {
  auto level__ = level ? _fbb.CreateString(level) : 0;
  auto component__ = component ? _fbb.CreateString(component) : 0;
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto ts__ = ts ? _fbb.CreateString(ts) : 0;
  return schematas::CreateSystemLog(
      _fbb,
      id,
      level__,
      component__,
      message__,
      ts__,
      ts_unix_ms);
}

struct SystemLogList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SystemLogListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOGS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::SystemLog>> *logs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::SystemLog>> *>(VT_LOGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LOGS) &&
           verifier.VerifyVector(logs()) &&
           verifier.VerifyVectorOfTables(logs()) &&
           verifier.EndTable();
  }
};

struct SystemLogListBuilder {
  typedef SystemLogList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_logs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::SystemLog>>> logs) {
    fbb_.AddOffset(SystemLogList::VT_LOGS, logs);
  }
  explicit SystemLogListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SystemLogList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SystemLogList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SystemLogList> CreateSystemLogList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::SystemLog>>> logs = 0) {
  SystemLogListBuilder builder_(_fbb);
  builder_.add_logs(logs);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SystemLogList> CreateSystemLogListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<schematas::SystemLog>> *logs = nullptr) {
  auto logs__ = logs ? _fbb.CreateVector<::flatbuffers::Offset<schematas::SystemLog>>(*logs) : 0;
  return schematas::CreateSystemLogList(
      _fbb,
      logs__);
}

inline const schematas::SystemLogList *GetSystemLogList(const void *buf) {
  return ::flatbuffers::GetRoot<schematas::SystemLogList>(buf);
}

inline const schematas::SystemLogList *GetSizePrefixedSystemLogList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schematas::SystemLogList>(buf);
}

inline bool VerifySystemLogListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schematas::SystemLogList>(nullptr);
}

inline bool VerifySizePrefixedSystemLogListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schematas::SystemLogList>(nullptr);
}

inline void FinishSystemLogListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::SystemLogList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSystemLogListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::SystemLogList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schematas

#endif  // FLATBUFFERS_GENERATED_SYSTEMLOGS_SCHEMATAS_H_
