// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRANSFORMATIONERRORS_SCHEMATAS_H_
#define FLATBUFFERS_GENERATED_TRANSFORMATIONERRORS_SCHEMATAS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace schematas {

struct TransformationError;
struct TransformationErrorBuilder;

struct TransformationErrorList;
struct TransformationErrorListBuilder;

struct TransformationError FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransformationErrorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_CORRELATION_ID = 6,
    VT_TOPIC = 8,
    VT_FAILED_FIELD = 10,
    VT_RULE_NAME = 12,
    VT_ERROR_MESSAGE = 14,
    VT_CREATED_AT = 16,
    VT_CREATED_AT_UNIX_MS = 18
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *correlation_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CORRELATION_ID);
  }
  const ::flatbuffers::String *topic() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TOPIC);
  }
  const ::flatbuffers::String *failed_field() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FAILED_FIELD);
  }
  const ::flatbuffers::String *rule_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RULE_NAME);
  }
  const ::flatbuffers::String *error_message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MESSAGE);
  }
  const ::flatbuffers::String *created_at() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_AT);
  }
  int64_t created_at_unix_ms() const {
    return GetField<int64_t>(VT_CREATED_AT_UNIX_MS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_CORRELATION_ID) &&
           verifier.VerifyString(correlation_id()) &&
           VerifyOffset(verifier, VT_TOPIC) &&
           verifier.VerifyString(topic()) &&
           VerifyOffset(verifier, VT_FAILED_FIELD) &&
           verifier.VerifyString(failed_field()) &&
           VerifyOffset(verifier, VT_RULE_NAME) &&
           verifier.VerifyString(rule_name()) &&
           VerifyOffset(verifier, VT_ERROR_MESSAGE) &&
           verifier.VerifyString(error_message()) &&
           VerifyOffset(verifier, VT_CREATED_AT) &&
           verifier.VerifyString(created_at()) &&
           VerifyField<int64_t>(verifier, VT_CREATED_AT_UNIX_MS, 8) &&
           verifier.EndTable();
  }
};

struct TransformationErrorBuilder {
  typedef TransformationError Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(TransformationError::VT_ID, id);
  }
  void add_correlation_id(::flatbuffers::Offset<::flatbuffers::String> correlation_id) {
    fbb_.AddOffset(TransformationError::VT_CORRELATION_ID, correlation_id);
  }
  void add_topic(::flatbuffers::Offset<::flatbuffers::String> topic) {
    fbb_.AddOffset(TransformationError::VT_TOPIC, topic);
  }
  void add_failed_field(::flatbuffers::Offset<::flatbuffers::String> failed_field) {
    fbb_.AddOffset(TransformationError::VT_FAILED_FIELD, failed_field);
  }
  void add_rule_name(::flatbuffers::Offset<::flatbuffers::String> rule_name) {
    fbb_.AddOffset(TransformationError::VT_RULE_NAME, rule_name);
  }
  void add_error_message(::flatbuffers::Offset<::flatbuffers::String> error_message) {
    fbb_.AddOffset(TransformationError::VT_ERROR_MESSAGE, error_message);
  }
  void add_created_at(::flatbuffers::Offset<::flatbuffers::String> created_at) {
    fbb_.AddOffset(TransformationError::VT_CREATED_AT, created_at);
  }
  void add_created_at_unix_ms(int64_t created_at_unix_ms) {
    fbb_.AddElement<int64_t>(TransformationError::VT_CREATED_AT_UNIX_MS, created_at_unix_ms, 0);
  }
  explicit TransformationErrorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TransformationError> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TransformationError>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TransformationError> CreateTransformationError(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> correlation_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> topic = 0,
    ::flatbuffers::Offset<::flatbuffers::String> failed_field = 0,
    ::flatbuffers::Offset<::flatbuffers::String> rule_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error_message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_at = 0,
    int64_t created_at_unix_ms = 0) {
  TransformationErrorBuilder builder_(_fbb);
  builder_.add_created_at_unix_ms(created_at_unix_ms);
  builder_.add_created_at(created_at);
  builder_.add_error_message(error_message);
  builder_.add_rule_name(rule_name);
  builder_.add_failed_field(failed_field);
  builder_.add_topic(topic);
  builder_.add_correlation_id(correlation_id);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TransformationError> CreateTransformationErrorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *correlation_id = nullptr,
    const char *topic = nullptr,
    const char *failed_field = nullptr,
    const char *rule_name = nullptr,
    const char *error_message = nullptr,
    const char *created_at = nullptr,
    int64_t created_at_unix_ms = 0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto correlation_id__ = correlation_id ? _fbb.CreateString(correlation_id) : 0;
  auto topic__ = topic ? _fbb.CreateString(topic) : 0;
  auto failed_field__ = failed_field ? _fbb.CreateString(failed_field) : 0;
  auto rule_name__ = rule_name ? _fbb.CreateString(rule_name) : 0;
  auto error_message__ = error_message ? _fbb.CreateString(error_message) : 0;
  auto created_at__ = created_at ? _fbb.CreateString(created_at) : 0;
  return schematas::CreateTransformationError(
      _fbb,
      id__,
      correlation_id__,
      topic__,
      failed_field__,
      rule_name__,
      error_message__,
      created_at__,
      created_at_unix_ms);
}

struct TransformationErrorList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransformationErrorListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ERRORS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::TransformationError>> *errors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schematas::TransformationError>> *>(VT_ERRORS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ERRORS) &&
           verifier.VerifyVector(errors()) &&
           verifier.VerifyVectorOfTables(errors()) &&
           verifier.EndTable();
  }
};

struct TransformationErrorListBuilder {
  typedef TransformationErrorList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_errors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::TransformationError>>> errors) {
    fbb_.AddOffset(TransformationErrorList::VT_ERRORS, errors);
  }
  explicit TransformationErrorListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TransformationErrorList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TransformationErrorList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TransformationErrorList> CreateTransformationErrorList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schematas::TransformationError>>> errors = 0) {
  TransformationErrorListBuilder builder_(_fbb);
  builder_.add_errors(errors);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TransformationErrorList> CreateTransformationErrorListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<schematas::TransformationError>> *errors = nullptr) {
  auto errors__ = errors ? _fbb.CreateVector<::flatbuffers::Offset<schematas::TransformationError>>(*errors) : 0;
  return schematas::CreateTransformationErrorList(
      _fbb,
      errors__);
}

inline const schematas::TransformationErrorList *GetTransformationErrorList(const void *buf) {
  return ::flatbuffers::GetRoot<schematas::TransformationErrorList>(buf);
}

inline const schematas::TransformationErrorList *GetSizePrefixedTransformationErrorList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schematas::TransformationErrorList>(buf);
}

inline bool VerifyTransformationErrorListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schematas::TransformationErrorList>(nullptr);
}

inline bool VerifySizePrefixedTransformationErrorListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<schematas::TransformationErrorList>(nullptr);
}

inline void FinishTransformationErrorListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::TransformationErrorList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTransformationErrorListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schematas::TransformationErrorList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schematas

#endif  // FLATBUFFERS_GENERATED_TRANSFORMATIONERRORS_SCHEMATAS_H_
